In [1]:
import numpy as np
from scipy import linalg  # Invoke with linalg
import scipy.linalg  # invoke with scipy.linalg

### **Matrix Matrix Multiplications operator @**

* `A@B` is a binary operator on A, B where A, B are both 2d array (matrices). It's equivalent to invoking `A.matnul(B)`. 

Mathematically, assuming $A$ is $n\times m$ and $B$ is $m\times k$

$$
(AB)_{i, j} = \sum_{k = 1}^{m} A_{i, k}B_{k, j}
$$

The $i, j$ th element of the product matrix $AB$ is the sum over the elementwise product on the $i$ th row of $A$ and $j$ th column of b. Notice that this means the operations is only possible if the number of columns of the first matrix matches the number of rows of the second matrix. 

Numpy Documentations [here](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html)

**Note**

The `@` operator is fine as long as you know for sure the left and right are both 2d arrays. 

**WARNING**

`np.matrix` object is deprecated and don't use it, they also have different bahavior under `*` operator. 

`*` THIS IS NOT MATRIX MATRIX PRODUCT, it's the [Hadamard Product](https://en.wikipedia.org/wiki/Hadamard_product_(matrices)), but it is matrix vector multiplications wehn `*` is invoked with `np.matrix`. 

In [2]:
m, n, k = 3, 5, 7  # m, n, k can be equal to 1, and that would be the same matrix vector product 
A = np.random.randint(10, size=(n, m))  # just random matrices with entries between 0 and 9. 
B = np.random.randint(10, size=(m, k))
print(A@B)

[[100  40  78  66  68 106  72]
 [ 90  40  72  60  64  88  60]
 [108  42  83  83  67 137  96]
 [ 22  28  24  48  14  40  36]
 [ 41  24  33  69  14  99  78]]


Matrix with 1d vector multiplication is also possible. And in that case the output vector will have the same dimension as the vector involved in the multiplication. 

In [17]:
u = np.random.randint(10, size=m)
(A@u).shape
print(A@u)

[58 54 67 34 44]


In [16]:
u = np.random.randint(10, size=(m,  1))
(A@u).shape
print(A@u)

[[132]
 [116]
 [149]
 [ 30]
 [ 68]]


### **Np.dot**

The following is copied straight from offcial numpy doc: [here](https://numpy.org/doc/stable/reference/generated/numpy.dot.html)

> numpy.dot
> 
> numpy.dot(a, b, out=None)
> 
> Dot product of two arrays. Specifically,
> 
> * **If both a and b are 1-D arrays, it is inner product of vectors (without complex conjugation)**.  <--- You are working with this for this class
> 
> * **If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred**.  <--- You are working with this for this class
> 
> * If either a or b is 0-D (scalar), it is equivalent to multiply and using numpy.multiply(a, b) or a * b is preferred.
> 
> * If a is an N-D array and b is a 1-D array, it is a sum product over the last axis of a and b.
> 
> * If a is an N-D array and b is an M-D array (where M>=2), it is a sum product over the last axis of a and the second-to-last axis of b:

This function is pretty general. It's meant for a special type of tensor product. But it reduces to usual product in linear alegbra when we have matrices and vector. 

**Demonstration:** 

In [18]:
print("Matrix Matrix product")
print(np.dot(A, B))
v = np.random.randint(10, size=(A.shape[1]))  # 1d vector , where A.shape[1]  is giving me the length of the first axis of the tensor A (The number of columns of A) 
print("Matrix with 1d vector")
print(np.dot(A, v))
print("Matrix with 2d vector")
print(np.dot(A, v.reshape(-1, 1)))

Matrix Matrix product
[[100  40  78  66  68 106  72]
 [ 90  40  72  60  64  88  60]
 [108  42  83  83  67 137  96]
 [ 22  28  24  48  14  40  36]
 [ 41  24  33  69  14  99  78]]
Matrix with 1d vector
[136 118 158  34  81]
Matrix with 2d vector
[[136]
 [118]
 [158]
 [ 34]
 [ 81]]


### **They Are Different**
They started to behave differently when tesors are involved. It's not going to be part of the class but it's better to make them clear. 

In [20]:
A = np.random.rand(2, 4, 2)
B = np.random.rand(2, 2, 4)
print((A@B).shape) # happend at the last 2 axis. 
print(np.dot(A, B).shape)  # multiplication happend at the last one axies. 

(2, 4, 4)
(2, 4, 2, 4)


When invoked with `np.array`, the operator `*` is not a matrix vector multiplication: 


In [24]:
A = np.random.rand(2,2)
b = np.ones((2, 1))
print(A*b)  
# The output should be a vector but the output is a matrix instead. 


[[0.92795971 0.80686233]
 [0.13112872 0.35541273]]


### **Other Materials from Last Week**

* `np.zeros((m, n))`: Making zeros array
* `np.empty((m, n))`: Making an array filled with nonsense numbers. 
* `A.reshape()`: chaging the shape the array to another shape but with the same number of elements. 