### **Table of Content**

**Anouncement**: 

* Join Piazza and get this notes. 
* Remember to study HW 1, 2 for exams. Both the concepts and the code involved. 
* Any questions on HW2? 

**This Section **
* Short Excercises about programming in general. 
  * Fibonacci Numbers with Forloops 
  * Fibonacci Numbers with Forloops and Arrays. 
* Excercises Iterative Methods and SVD solving of equations. 
* HW3 Guide

In [1]:
import numpy as np
import scipy.linalg

### **Exercise 1: Forloops Fibonacci Number**

The Fibonacci Number is a sequence of numbers starting with 1 as the first 2 terms, and the sequences satisfies: 

$$
\begin{cases}
    a_{n + 2} &= a_{n + 1} + a_n 
    \\
    a_{1} = a_0 &= 1 & 
\end{cases}
$$

**Objective**: 

Write a function that accepts an integer, assuming it's non-negative, it returns $a_n$. For example: 

```python
FibboTermAt(0)
1
FibboTermAt(1)
1
FibboTermAt(4)
5
```

**Question**: 

How would you write the code inside the function to build up the sequence? How many iterations should there be? What if the input has $0\le N \le1$? 

<details>

<summary>Hints</summary>

* Use 3 variables to keep track of the sequence, where 2 variables are keeping track of the sequence. 

</details>



In [2]:
def FibboTermAt(n):
    PreviousTerm = 1
    PreviousPreviousTerm = 1
    if n <= 1:
        return PreviousTerm
    for _ in range(n - 1): 
        NextTerm = PreviousTerm + PreviousPreviousTerm
        PreviousPreviousTerm = PreviousTerm
        PreviousTerm = NextTerm
    return NextTerm
    

In [3]:
Sequence = []
for I in range(21): 
    Sequence.append(FibboTermAt(I))
print(Sequence)

[1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946]


### **Exercise 2: Forloops Fibonacci Sequence**

**Objective**

Write a function that accepts an integer, assuming it's non-negative, it returns the first n sequences of Fibbonacci Numbers in an numpy array. 

**Examples**

```

FibboSeq(11)
[1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144]

```

<details>
    <summary>Hints</summary>
    <ul>
        <li>Build an empty array using the input `n`, and put in the first 2 terms</li>
        <li>Use the forloops and update the `n+2`'term using the `n+1` and `n` th term</li>
    </ul>
</details>



In [6]:
def FibboSeq(n):
    if n <= 1:
        return 1
    FibbNumbers = np.zeros(n, dtype=np.int64)
    FibbNumbers[:2] = 1
    for II in range(2, n):
        FibbNumbers[II] = FibbNumbers[II - 1] + FibbNumbers[II - 2]
    
    return FibbNumbers


In [7]:
print(FibboSeq(20))

[   1    1    2    3    5    8   13   21   34   55   89  144  233  377
  610  987 1597 2584 4181 6765]


### **Exercise 3: Eigenvalues and Fibbonacci Number**

We can use Eigenvalue decomposition to improve the speed of computing the nth Fibbonacci Numbers. Observe the following: 

$$
\begin{bmatrix}
    0 & 1
    \\
    1 & 1
\end{bmatrix}
\begin{bmatrix}
    a_{n}\\a_{n + 1}
\end{bmatrix}
= 
\begin{bmatrix}
    a_{n + 1} \\ a_{n + 1} + a_{n}
\end{bmatrix}
=
\begin{bmatrix}
    a_{n + 1} \\ a_{n + 2}
\end{bmatrix}
$$

For example, n = 5: 
$$
\begin{bmatrix}
    0 & 1
    \\
    1 & 1
\end{bmatrix}
\begin{bmatrix}
    5 \\8
\end{bmatrix}
= 
\begin{bmatrix}
    8 \\ 13
\end{bmatrix}
$$

If, we started with the number "8, 13", we want to compute the next 2 numbers in the sequence, how would we do that with linear algebra in numpy? 


**Discussion with peers**

* What is the matrix that when we multiply the vector `[9; 13]` so that we can get the next 2 terms: `[21; 34]`? 

<details>

<summary>Answer</summary>

* Multiply the matrix a second time

$$
\begin{bmatrix}
    0 & 1
    \\
    1 & 1
\end{bmatrix}^2
$$

</details>


In [9]:
v = np.array([8, 13]).reshape(-1, 1)
M = np.array([[0, 1], [1, 1]])
M@M@v

array([[21],
       [34]])

**Prompt:** 
What is the general patterns here? And how would be make use of the Eigenvalue decomposition for solving this problem (computing the nth fibbonacci number)? Discuss with you peers. 

**Objective**

Fill in the function below, so that when it gets the input `n`, it computes the `n` th term in the fibb sequence just like that first exercise we did. 

**Helpful Functions Python**

|Function |Description|
|-----|--------|
|[np.linalg.eig](https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html)| Compute eigenvalues & eigenvectors of a non-symmetric matrix. |
|[np.diag](https://numpy.org/doc/stable/reference/generated/numpy.diag.html)| If the input is a vector of size `n`, then the vector is filled into the diagonal of a zero matrix with size `n x n`, then it returns the matrix. If input is a matrix, then it extracts out the diagonal elements of the matrix and returns it as a vector. |
|[np.linalg.solve](https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html)| solve a system Ax = b|

**Helpful Function Matlab**
|Function| Description|
|-------|---------|
|[eig](https://www.mathworks.com/help/matlab/ref/eig.html)|Returns the eigevalues & eigenvectors of a general matrix. Both as matrices|

<details>

<summary>Hints</summary>

* First, we need to realize that, the repeatedly multiplying the matrix is involved. 

* Second, we need to remember how to use `np.eig`, `np.solve`, and the values returned to code it up. 

</details>

<details>

<summary>Answer</summary>

* Observe that, to get from `a_0, a_1` to `a_{n}, a_{n + 1}`, we need to multiply by `n`  times, and assuming that the matrix has eigen decomposition $X\Lambda X^{-1}$ where $X$ is the matrix whose columns are the eigenvectors, then:

$$
\begin{bmatrix}
    0 & 1
    \\
    1 & 1
\end{bmatrix}^n = \underbrace{X\Lambda X^{-1}X\Lambda X^{-1} \dots X\Lambda X^{-1}}_{\text{n times}} = X\Lambda^nX^{-1}
$$

Then we just raise power on the diagonal matrix and then multiply both side by the the matrix $X$, and inverse of $X$. 

</details>


In [25]:
def EigenComputeFibbTo(n):
    if n <= 1:
        return 1
    x0 = np.array([[1], [1]])
    M = np.array([[0, 1], [1, 1]])
    w, V = np.linalg.eig(M)
    W = np.diag(w)
    y = V@W**(n - 1)@np.linalg.solve(V, x0)
    return y[0, 0]


In [26]:
for II in range(20):
    print(EigenComputeFibbTo(II))

1
1
0.9999999999999998
1.9999999999999996
2.999999999999999
4.999999999999999
8.0
13.0
21.0
34.00000000000001
55.00000000000001
89.00000000000001
144.0
233.00000000000003
377.0000000000001
610.0000000000001
987.0000000000003
1597.0000000000005
2584.000000000001
4181.000000000002


### **Use SVD to Find Solutions to a Linear System**



### **SVD Decomposition**

**Python Relevant Function**

|Python Functon |Description|
|-----|-----|
|[np.linalg.svd](https://numpy.org/doc/stable/reference/generated/numpy.linalg.svd.html)|returns $U, \sigma, V^H$, and notice that the singular values are returned as a vector. |
|[np.diag](https://numpy.org/doc/stable/reference/generated/numpy.diag.html)| If the input is a vector of size `n`, then the vector is filled into the diagonal of a zero matrix with size `n x n`, then it returns the matrix. If input is a matrix, then it extracts out the diagonal elements of the matrix and returns it as a vector. |

**Matlab Relevant Functions**

|Matlab Function|Description|
|------|-----|
|[svd](https://www.mathworks.com/help/matlab/ref/double.svd.html)|Returns $U, \Sigma, V$, all as matrices. |


Suppoes that SVD is performed on $A$, where $A$ is $m\times n$ The decomposition is: 

$$
A = U\Sigma V^T
$$
Where, $U$ could be $m\times m$ or $m\times \min(m, n)$ which shape it takes depends on parameters passed into the function. $\Sigma$ is a diagonal matrix full of singular values of the matrix $A$, and they are all positive real numbers, $\Sigma$ can be in shape of $m\times n$ or $\min(m, n)\times \min(m, n)$, and $V^T$ is a matrix with in the shape of $m\times n$ or $\min(m, n)\times n$. 

The matrix $U, V$ are called unitary/orthonormal. Their inverse is the transpose conjugate of itself. Then, one can assert that the inverse of matrix $A$ when $A$ happens to be square would be: 

$$
A^{-1} = (U\Sigma V^T)^{-1} = V(\Sigma)^{-1}U^T
$$

Because $\Sigma$ is diagonal, it's inverse is just taking the reciprical of all the elements in the diagonal of $\Sigma$. 


**Exercise**

* Implement the method `SolveViaSVD` below, using the $U, \Sigma, V^T$ matrix from `np.linalg.svd`. Execute the cell and compare the output from both of these solver. 
* Disscuss, can the matrix be solved using iterative method such as Guass Sediel or Jacobi and WHY? 




In [30]:
def JacobiIterate(A, b, x_guess=None, tol=1e-8):
    """
        Performs Jacobi iteration on the system Ax = b, until the residual has infnorm less than 1e-10. 
        (Please take a read on this method after class and understand how iterative methods are implemented in real life)
    """
    x_guess = b if x_guess is None else x_guess
    d = np.diag(A)  # d: Vector of diagonal elements of A. 
    D = np.diag(d)  # D: Gotten by setting all the non-diagonal part of the matrix A to zero. 
    LpU = A - np.diag(d)  # The non diagonal part of the matrix A. 
    guesses = [x_guess]  # All the guesses are stored in python native array
    while True:
        
        guesses.append(np.linalg.solve(D, (b - LpU.dot(guesses[-1])))) # Acccumulate the results. 
        if np.linalg.norm(guesses[-1] - guesses[-2]) < tol:  # Break conditions. 
            break
    return guesses[-1]

def SolveViaSVD(M, c):
    # your code here, return the inverse of the matrix X using SVD
    U, s, Vh = np.linalg.svd(M)
    Sinv = np.diag(1/s)
    return  Vh.T@Sinv@U.T@c




N = 10
b = np.random.rand(N, 1)
X = np.random.randn(N, N) 
X += np.diag(np.sum(np.abs(X), axis=1))  # Row sum. 
print(f"Solution from iterative method is: \n{JacobiIterate(X, b)}")
print(f"Solution from your method is: \n{SolveViaSVD(X, b)}")





Solution from iterative method is: 
[[0.12670668]
 [0.07008797]
 [0.06938522]
 [0.03130241]
 [0.00555335]
 [0.04748927]
 [0.04497768]
 [0.09084911]
 [0.08363808]
 [0.06179282]]
Solution from your method is: 
[[0.12670668]
 [0.07008797]
 [0.06938523]
 [0.03130241]
 [0.00555335]
 [0.04748927]
 [0.04497768]
 [0.09084911]
 [0.08363808]
 [0.06179282]]


### **HW3 Guide and Clarifications**


Piazza HW3 Errata Post: [here](https://piazza.com/class/kuflna54rev3ly?cid=83 )

* A1: The "Correlation Matrix" is meant to be the direct pairwise dot products between each columns from the matrix X, **for the sake of the homework normalization and putting it to zero mean is not needed**. 
  * In practice, correlation matrix is from the Pearson Correlation Coefficients, which involves dividing the covariance by the product of the standard deviation for all columns of samples. But for this HW, we don't need to do this.
* A2, A3: Index starts with one, not zero. Need to translate the indices. 
* A4: `[1, 313, 512, 5, 2400, 113, 1024, 87, 314, 2005]`, these indeices are one based, to use them in python, please subtract one. When uploading results for the images with maximal correlations, add one to the index of the images (python starts with 0). 