In [2]:
import numpy as np

### **Lecture 1**

* Import numpy 
* `np.array` and `np.matrix`
* `display`
* `transpose`
* `conjugate`
* boolean masking 



### **Python Native Arrays**: 
* Native data structure that can store references to literally everything. 
* Warning they are totally not the same thing as numpy array. 


In [3]:
Arr1 = [1, 2, 3]
Arr2 = [1, 2.9, "g", Arr1]
Arr3 = Arr1 + Arr2  # addition is concatenation. 
print(Arr1)
print(Arr2)
print(Arr3)


[1, 2, 3]
[1, 2.9, 'g', [1, 2, 3]]
[1, 2, 3, 1, 2.9, 'g', [1, 2, 3]]


### **Numpy Array**
* They are vectors and matrices, and even tensor, their type is homogeneous. 
* They are implemented in C. 
* They can be multi-dimensional array. 

In [4]:
Arr1 = np.array([1, 2, 3])  # 1d numpy array. 
Arr2 = np.array([3, 4, 5])
Arr3 = Arr1 + Arr2  # adding is element wise. 
print(Arr1)
print(Arr2)
print(Arr3)

[1 2 3]
[3 4 5]
[4 6 8]


In [5]:
M = np.matrix([1, 2, 3])
print(M)                        # observe it's a nested array. 
M2 = np.array([[1, 2, 3]])
print(M2)
print(f"The size is: {M2.shape}")  # String interpolations in python 3.6+ 


[[1 2 3]]
[[1 2 3]]
The size is: (1, 3)


### **Matrix Vector Multiplications**
* Multiplying a matrix by a vector from the right side. 
* `*` is the wrong operator to do it, it's the elementwise operator. 

In [6]:
A3By3Matrix = np.array([[1, 2, 3], 
                        [3, 4, 5], 
                        [6, 7, 7]])
AcolumnVec = np.array([[1], 
                       [0], 
                       [0]])
display(A3By3Matrix @ AcolumnVec)
display(np.dot(A3By3Matrix, AcolumnVec)) # recommend
display(A3By3Matrix*AcolumnVec)

array([[1],
       [3],
       [6]])

array([[1],
       [3],
       [6]])

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [7]:
### Warning, Don't use the matrix class as it's been deprecated for usage in numpy. 
# A3By3Matrix = np.matrix([[1, 2, 3], 
#                         [3, 4, 5], 
#                         [6, 7, 7]])
# AcolumnVec = np.matrix([[1], 
#                        [0], 
#                        [0]])
# display(A3By3Matrix @ AcolumnVec)
# display(np.dot(A3By3Matrix, AcolumnVec))
# display(A3By3Matrix*AcolumnVec)

### **Array Reshape**
* You can change the shape of the array while keeping elements the same
* Transposing is shapeshiting


In [17]:
Arr1 = np.random.rand(3, 4)
display(Arr1)
Arr1 = Arr1.reshape(-1)
display(Arr1); display(Arr1.shape)
Arr1 = Arr1.reshape(4, 3)
display(Arr1); display(Arr1.shape)
Arr1 = Arr1.reshape(12, 1, 1)
print(Arr1.shape)

array([[0.64243063, 0.75565054, 0.89255057, 0.3092381 ],
       [0.11507609, 0.59442271, 0.31436872, 0.91006157],
       [0.77537834, 0.42011335, 0.6501219 , 0.40163309]])

array([0.64243063, 0.75565054, 0.89255057, 0.3092381 , 0.11507609,
       0.59442271, 0.31436872, 0.91006157, 0.77537834, 0.42011335,
       0.6501219 , 0.40163309])

(12,)

array([[0.64243063, 0.75565054, 0.89255057],
       [0.3092381 , 0.11507609, 0.59442271],
       [0.31436872, 0.91006157, 0.77537834],
       [0.42011335, 0.6501219 , 0.40163309]])

(4, 3)

(12, 1, 1)


In [9]:
Arr1 = Arr1.reshape(-1, 2)
display(Arr1); display(Arr1.shape)

array([[0.02406516, 0.36122417],
       [0.91043403, 0.46928237],
       [0.31896376, 0.48930815],
       [0.49119974, 0.87595693],
       [0.04038996, 0.09883412],
       [0.48895355, 0.04836949]])

(6, 2)

In [10]:
Arr1 = Arr1.T
display(Arr1); display(Arr1.shape)

array([[0.02406516, 0.91043403, 0.31896376, 0.49119974, 0.04038996,
        0.48895355],
       [0.36122417, 0.46928237, 0.48930815, 0.87595693, 0.09883412,
        0.04836949]])

(2, 6)

### **Indexing**

#### Warning: **Python takes this to a whole new level and it's very complicated**: [here](https://numpy.org/doc/stable/reference/arrays.indexing.html) are more information. 

* Boolean array indexing and array filtering. 

In [11]:
Arr1 = np.random.rand(1, 10)
print(Arr1)
BoolMask = Arr1 > 0.5
print(BoolMask)
print(Arr1[BoolMask]) # Observe that the shape has changed back into a 1d array. 

[[0.99817317 0.18299498 0.36117398 0.57509361 0.41336975 0.85804006
  0.37588714 0.40357103 0.43505415 0.39914376]]
[[ True False False  True False  True False False False False]]
[0.99817317 0.57509361 0.85804006]


### **Scientific Floating Points**
* Scientific Floating points 
* Other special values

In [12]:
# Scientific Floating points
print(1e-4) 
print(float("inf"))
print(float("nan"))


0.0001
inf
nan


### **Types and dtypes**
* Array, numpy has a name that refers to their types in python, use the `type` function to query the type. 
* Sometimes, they might cause trouble when we try to convert them. 
* 

In [18]:
Arr1 = np.array([2, 2, 2])
type(Arr1)
print(Arr1.dtype)

int32


In [14]:
print(Arr1**33)  # no conversion and integer overflow. 
print(Arr1**33.0) # conversion
print(Arr1**(-3)) # error

[0 0 0]
[8.58993459e+09 8.58993459e+09 8.58993459e+09]


ValueError: Integers to negative integer powers are not allowed.

### **Bisection Method**
* The function is continous, and crosses the x-axis
* It keeps the sign on the left and right boundary different, this is the algorithm invariant. 

In [ ]:
xr = -2.8  # left boundary with 
xl = -4    # right boundary
# f(xr) f(xl) share different signs
print(np.sign(np.exp(xr) - np.tan(xr)))
print(np.sign(np.exp(xl) - np.tan(xl)))

for j in range(0, 100):
    xc = (xr + xl)/2             # find middle
    fc = np.exp(xc) - np.tan(xc) # comput function value at the middle point. 
    if (fc > 0):                 # if it's positive (mathcing the right boundary), make it the new left boudary  o. 
        xl = xc
    else:                        # make the middle the new right boundary. 
        xr = xc
    if ( abs(fc) < 1e-5 ):       # if the value of the middle point is close enough to zero. 
        display(xc)
        break

-1.0
1.0


-3.0964111328124995

### **The Newton's Rasphason Method**

$$
x_{k + 1} = x_{k} - \frac{f(x_k)}{f'(x_k)}
$$

Preconditions: 

* The functioon's derivative is continuous. 
* The initial guess doesn't give a point that has zero deriative. 


In [ ]:
x = np.array([-4])  # initial guess

for j in range(1000):
    x = np.append(
        x, x[j] - (np.exp(x[j]) - np.tan(x[j])) / (np.exp(x[j]) - 1 / np.cos(x[j]) ** 2)
    )
    fc = np.exp(x[j + 1]) - np.tan(x[j + 1])

    if abs(fc) < 1e-5:
        break

print(x[j + 1])
print(fc)


# (2) Pre-allocating the space (should run faster, but you end up wasting some space)
x = np.empty(1001)
x[0] = -4 

for j in range(1000):
    x[j + 1] = x[j] - (np.exp(x[j]) - np.tan(x[j])) / (
        np.exp(x[j]) - 1 / np.cos(x[j]) ** 2
    )
    fc = np.exp(x[j + 1]) - np.tan(x[j + 1])

    if abs(fc) < 1e-5:
        break

print(x[j + 1])
print(fc)


